language: scala
sudo: required
dist: trusty

scala:
  - 2.12.4
  - 2.11.12

jdk:
  - oraclejdk8

services:
  - mongodb

cache:
  directories:
    - $HOME/.sbt/0.13/dependency
    - $HOME/.sbt/boot/scala*
    - $HOME/.ivy2/cache

script:
  - sbt ++$TRAVIS_SCALA_VERSION clean test;

before_cache:
  - du -h -d 1 $HOME/.ivy2/cache
  - du -h -d 2 $HOME/.sbt/
  - find $HOME/.sbt -name "*.lock" -type f -delete
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -type f -delete
